name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Just sleep for a bit
        run: /bin/sleep 10
        shell: bash
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install bats
        run: npm install -g bats
      - name: Run bats
        run: bats -v
